### ISSUE TITLE
Spring.Web.AspNetCore Support?

### ISSUE THREAD

**Issue by superboy1984** [spring-projects/spring-net#210]
any plan for supprort AspNetCore?

**Comment by lahma** [comment]
No such plans, but if you would like to champion the feature and build it I think it would be very welcome.  Biggest obstacle probably is that Spring.NET doesn't have scoped objects concept.

**Comment by lahma** [comment]
@maulik-modi [tests are run on both Windows and Linux](https://github.com/spring-projects/spring-net/actions/runs/1105761071). So the library should work on both platforms, but there might be some differences not spotted yet as 3.0 brought the cross-platform support.

**Comment by maulik-modi** [comment]
@lahma , I am thinking to contribute - Spring.Microsoft.DependencyInnjection package if 3.0 
 is stable and test cases are passing 

Inspiration: https://github.com/JasperFx/lamar/tree/master/src/Lamar.Microsoft.DependencyInjection

**Comment by lahma** [comment]
Sounds good!

**Comment by maulik-modi** [comment]
@lahma , I see that https://github.com/spring-projects/spring-net/actions/runs/1105761071 
runs windows builds using .net 4.6.X and 
runs Linux builds using .net 5.0

Linux build is passing these projects, it does not include Spring.Web.Tests because System.web.mvc is not cross platform, Is there any way Build/Test project status can be published on https://github.com/spring-projects/spring-net e.g. Quartz project shows build status
![image](https://user-images.githubusercontent.com/34910430/130397670-bb96e8cf-9c28-4edf-950c-da633ce21804.png)

- Spring.Core.Tests.csproj
- Spring.Aop.Tests.csproj
- Spring.Data.Tests.csproj
- Spring.Testing.NUnit.csproj 
- Spring.Testing.Microsoft.csproj 
- Spring.Scheduling.Quartz3.Tests.csproj
- Spring.Data.NHibernate5.Tests.csproj
- Spring.Messaging.Nms.Tests.csproj

**Comment by lahma** [comment]
I've added some badges to main readme, there's no sub-project level info for builds as everything is built and tested together.

**Comment by maulik-modi** [comment]
@lahma thats superb; In the past I had used Coverlet to generate code coverage reports with Jenkins,  https://samlearnsazure.blog/2021/01/05/code-coverage-in-github-with-net-core/ help getting started
This will bring more transparency and confidence

**Comment by lahma** [comment]
A PR would be nice 😉

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
