### ISSUE TITLE
Spring.NET 2.0 release

### ISSUE THREAD

**Issue by chrisdrobison** [spring-projects/spring-net#82]
You guys mentioned months ago this was going to be released months. When is 2.0 targeted to be released officially and the Nuget package updated?

**Comment by sbohlen** [comment]
This will likely be officially 2.0 GA this coming weekend.

**Comment by ericklombardo** [comment]
+1

**Comment by hallissons** [comment]
+1

Em quarta-feira, 28 de janeiro de 2015, Erick Lombardo <
notifications@github.com> escreveu:

**Comment by zhangyaoxing** [comment]
Finally. Good to know.

**Comment by kamiff** [comment]
+1

**Comment by ncpga** [comment]
+1. Cant wait.

**Comment by piolo108** [comment]
Will this release support NHibernate 4?

**Comment by sbohlen** [comment]
Yes, that support is already in the MASTER branch and so would be included in any subsequent release.

-Steve B.

-----Original Message-----

**Comment by sbohlen** [comment]
Just as an update to this issue, we've just posted an updated RC2 build to NuGet.

Our thinking is that its been so long since the RC1 release that there have actually been many updates/changes since the RC1 release.  This makes RC1 unable to function as an actual Release Candidate.

Assuming that no deal-breakers are uncovered by anyone from the RC2 build, our plan is now release 2.0.0GA approximately 2 weeks from now.

**Comment by chrisdrobison** [comment]
I've noticed that the RC 2 Nuget packages have a common.logging dependency of >= 1.2.0. Shouldn't that get changed to 3.0?

**Comment by sbohlen** [comment]
Ouch -- nice catch, yes, I'll update that immediately.  Thank, this sort of
oversight is *exactly* the sort of thing that RC is designed to catch!

Cheers,

-Steve B.

Steve Bohlen
sbohlen@gmail.com
http://blog.unhandled-exceptions.com
http://twitter.com/sbohlen
