### ISSUE TITLE
when spring.net support EF6 and WebApi?

### ISSUE THREAD

**Issue by kindywu** [spring-projects/spring-net#85]
i think EF6 is better orm framework,can spring.net 2.0 support it?

**Comment by sbohlen** [comment]
Just fork the code and submit a pull-request; we'd love to have the contributions!

**Comment by sbohlen** [comment]
FWIW, there is already support for WebAPI as part of our support for ASP.NET MVC 4 and 5; are you thinking about support of some kind beyond what is already provided for there --?

**Comment by djechelon** [comment]
Where can I find documentation about Spring and earlier versions of EF? I'm intersted too and I'm available to contribute if I have to override some classes from the Spring framework to my project. I simply need to understand how to **correctly** set up transactions and EF/Spring best practices. I'm struggling from weeks with two Spring-EF projects to work on

**Comment by sbohlen** [comment]
I may have inadvertently given the wrong impression.  I was offering that Spring.Net has support for WebAPI as part of its MVC4 and MVC5 support (the two versions of MVC that offer WebAPI).

Spring.Net has no support (at this time) for EF and so there's no documentation to which I can point you per se.  If you (or anyone else) is interested in working on such an effort, we'd be happy to assist with guidance, etc. where we can.

I'd suggest starting by conceptually "mapping" each concept from NH to its corollary in EF (e.g., NH session is like an EF DbContext, and so on).  Then attempt to mimic the classes, etc. in Spring.NHibernate that are necessary to work with those same concepts in EF.

Make sense --?

**Comment by djechelon** [comment]
Oh I see. Actually I don't need full 1:1 mapping with NH features, because EF != NH and EF is a complete ORM per se.

I'm working hard in understanding how internally both Spring and EF work in order to come up with a working code-pattern for setting up transactions and DB interoperability (EF doesn't support AOP transactions out of the box, but works great with transactions).

I won't go in the deep today with my post but I believe that, at least according to my specific needs (transactions + DB interoperability) there should be no need to create a brand new Spring.Data.EF package. EF supports DB interop per se, as soon as you inject the connection string and [watch out](https://stackoverflow.com/questions/28172859/switching-between-mysql-sql-server-in-ef6) for pitfalls between MSSQL and MySQL.

Today I found that setting up [Transaction] with a TxScopeTransactionManager does nothing at all when used with EF when the DbContext is instantiated with new(), unless *I implement* a proper factory that injects the current connection/transaction into the DbContext (see https://msdn.microsoft.com/en-us/data/dn456843.aspx).

More in general, an integration between Spring and EF could offer these features I don't personally need in my project, but can be desirable by others:

 - Exception translating (EF has its own exceptions)
 - Exposing DbSet<T> as injectable/autowireable object, because DbSet<T> implements the DAO pattern per se

**Comment by djechelon** [comment]
Just one note for sake of discussion, I hope I'll be implementing it in the next few weeks.
In order to autowire a [Transaction]al DbContext I wanted to do the following:

 1. Classes that need DbContext during a transaction must call a GetDbContext() method that simply calls IApplicationContext's GetObject method
 2. Define DbContext as an object with a factory and a create method
 3. Build the factory class!

Basically the factory class has a reference to the IPlatformTransactionManager and when the factory method is called it checks for an existing transaction. If the transaction exists, grab the connection and return a DbContext initialized with that connection but **not owning it** (as of [constructor](https://msdn.microsoft.com/it-it/library/gg696604%28v=vs.113%29.aspx)). If no transaction is active, it will be my choice to either throw (like Propagation.MANDATORY) or return a fresh new DbContext owning the connection (like Propagation.REQUIRED).

What do you think about this design? It looks trivial to me but shall do the trick of transactions

**Comment by djechelon** [comment]
Hi, another comment on Transactions and Entity Framework.

I initially set up `TxScopeTransactionManager` on my app. I **thought** I had to set up a proper DbContext factory to wire an existing `DbConnection` into it in order to run transactions fine.

I was wrong. Even issuing `using(MyDbContext ctx = new MyDbContext())` in a method marked `[Transaction]` works, because I happened to find the following stack trace in my logs

    2015-02-19 13:09:05,525 | 20 | ERROR | DiagnosticoSite.Controllers.BaseController | Failure on Transaction Scope rollback.
    Spring.Transaction.TransactionSystemException: Failure on Transaction Scope rollback. ---> System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
    in MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
    in MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
    in MySql.Data.MySqlClient.MySqlDataReader.NextResult()
    in MySql.Data.MySqlClient.MySqlDataReader.Close()
    in MySql.Data.MySqlClient.MySqlCommand.ResetReader()
    in MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
    in MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
    in MySql.Data.MySqlClient.MySqlTransaction.Rollback()
    in MySql.Data.MySqlClient.MySqlTransactionScope.Rollback(SinglePhaseEnlistment singlePhaseEnlistment)
    in MySql.Data.MySqlClient.MySqlPromotableTransaction.System.Transactions.IPromotableSinglePhaseNotification.Rollback(SinglePhaseEnlistment singlePhaseEnlistment)
    in System.Transactions.DurableEnlistmentAborting.EnterState(InternalEnlistment enlistment)
    in System.Transactions.TransactionStateAborted.EnterState(InternalTransaction tx)
    in System.Transactions.Transaction.Rollback()
    in System.Transactions.TransactionScope.InternalDispose()
    in System.Transactions.TransactionScope.Dispose()
    in Spring.Data.Core.TxScopeTransactionManager.DoRollback(DefaultTransactionStatus status)
    --- Fine della traccia dello stack dell'eccezione interna ---
    in Spring.Data.Core.TxScopeTransactionManager.DoRollback(DefaultTransactionStatus status)
    in  Spring.Transaction.Support.AbstractPlatformTransactionManager.ProcessRollback(DefaultTransactionStatus status)
    in Spring.Transaction.Interceptor.TransactionAspectSupport.CompleteTransactionAfterThrowing(TransactionInfo transactionInfo, Exception exception)
    in Spring.Transaction.Interceptor.TransactionInterceptor.Invoke(IMethodInvocation invocation)

The exception is not important by itself, but simply means, and I hope it could be expanded in the future within Spring.Data documentation, that using `TxScopeTransactionManager` is sufficient to have Entity Framework 6 "autowire" itself to the existing transaction, if any. When an exception propagates, Spring.Data rollbacks the **Spring** transaction causing the underlying **EF** transaction to rollback. Could be reproduced in a sample test.

I have not experimented yet with composite/propagated/nested transactions (even because MySQL doesn't support nested transactions), but in response to @kindywu I could say that, at least for the transactions aspect, Spring 1.3, and supposedly 2.0, are perfectly compatible with EF 6.

Personally, I'm not yet interested in any other aspect of Spring/EF. Apart from exception translating, I'd ask @sbohlen if there could be other aspects to take into consideration for a possible `Spring.Data.EF6` implementation

**Comment by hasanuzun** [comment]
I have already created a project as Spring.Data.EF as likes Spring.Data.NHibernateX. It is working properly in sample project. I will commit it as soon as possible.

**Comment by sbohlen** [comment]
That would be great-- we're eager to review and incorporate it into the project!

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
