### ISSUE TITLE
Common.Logging 3.0

### ISSUE THREAD

**Issue by chrisdrobison** [spring-projects/spring-net#92]
Can't use common.logging 3.0 with these libraries since they haven't been compiled against them.

**Comment by sbohlen** [comment]
This is a known issue with NuGet (see http://nuget.codeplex.com/discussions/578411 and the several issues in other projects linked to from that post for more details) in packages that depend upon Common.Logging (e.g., beyond merely Spring.NET).

The Common.Logging dependency in the MASTER branch here has already been updated to CL 3.0.0 and so when Spring.NET 2.0.0 GA is released (likely in the next week or so) this issue will resolve itself.  In the mean time, the only course of action for consumers of packages that haven't released updates properly recompiled against Common.Logging 3.0.0 is to _not_ update other dependencies to the 3.0.0 version of Common.Logging.

Because this is already addressed in MASTER, I'm going to close this issue (even though technically the fix won't be accessible until we push 2.0.0 GA in the next week or two).
