### ISSUE TITLE
System.ArgumentException : The transaction specified for TransactionScope has a different IsolationLevel than the value requested for the scope.

### ISSUE THREAD

**Issue by ynauls** [spring-projects/spring-net#96]
After upgrading from 1.3.2 to 2.0-RC2, I am getting the following error:

Spring.Transaction.CannotCreateTransactionException : Transaction Scope failure on begin
System.ArgumentException : The transaction specified for TransactionScope has a different IsolationLevel than the value requested for the scope.
Parameter name: transactionOptions.IsolationLevel.

Sample code below.

```
public class Service1
{
	[Transaction(TransactionPropagation.Required)]
	public virtual void MethodWithRequired(TransferUserDto userToTransferDto)
	{
		Service2.MethodWithNotSuppored();
	}
}

public class Service2
{
	[Transaction(TransactionPropagation.NotSupported)]
	public virtual void MethodWithNotSuppored()
	{
		// do something, expecting to suspend current transaction
	}
}
```
I tried setting the isolation level for both Transaction attributes with no luck.

**Comment by sbohlen** [comment]
Excellent -- thanks for the issue report (and the repro).  We'll take a look at this ASAP.

**Comment by piolo108** [comment]
Great, thank you.  My error sounds similar to this bug https://jira.spring.io/browse/SPRNET-1434

**Comment by piolo108** [comment]
Update, after further troubleshooting, I noticed that the previous developers implemented a custom version of "HibernateTxScopeTransactionManager" with a few differences to fix a bug in v1.3.2 (comments don't specify the bug), after re-configuring to use the following:

Spring.Data.NHibernate.HibernateTxScopeTransactionManager, Spring.Data.NHibernate4

one of my failing unit tests is now passing, however, one still fails with a new error: stack trace (similar to https://jira.spring.io/browse/SPRNET-1434):

System.InvalidOperationException : No value for key [NHibernate.Impl.SessionFactoryImpl] bound to thread [Runner thread]
   at Spring.Transaction.Support.TransactionSynchronizationManager.UnbindResource(Object key)
   at Spring.Data.NHibernate.HibernateTxScopeTransactionManager.DoSuspend(Object transaction)
   at Spring.Transaction.Support.AbstractPlatformTransactionManager.Suspend(Object transaction)
   at Spring.Transaction.Support.AbstractPlatformTransactionManager.HandleExistingTransaction(ITransactionDefinition definition, Object transaction, Boolean debugEnabled)
   at Spring.Transaction.Support.AbstractPlatformTransactionManager.GetTransaction(ITransactionDefinition definition)
   at Spring.Transaction.Interceptor.TransactionAspectSupport.CreateTransactionIfNecessary(ITransactionAttribute sourceAttr, String joinpointIdentification)
   at Spring.Transaction.Interceptor.TransactionInterceptor.Invoke(IMethodInvocation invocation)

My unit test is setup in the following:

[TestFixture]
public class MyTestSuite : AbstractTransactionalSpringContextTests
{
        [Test]
        public void MyTest()
        {
                 Service1.MethodWithNotSuppored1();
        }
}

[Transaction(TransactionPropagation.Supports, ReadOnly = true)]
public class Service
{
        [Transaction(TransactionPropagation.NotSupported)]
        public virtual void MethodWithNotSuppored1()
        {
                MethodWithNotSuppored2(); // error is thrown here
        }
      
        [Transaction(TransactionPropagation.NotSupported)]
        public virtual void MethodWithNotSuppored2()
        {
                
        }
}

**Comment by sbohlen** [comment]
Yes, TX management in NH itself has been a bit of a mess for some time now (especially on rollback/dispose and when used in combination with the .net TxScope attribute).  This led us to introduce the HibernateTxScopeTransactionManager,  designed to handle NH transactions in the context of the .net TxScope attribute (instead of only the Spring.Net Transaction attribute).

I'll definitely review your failing test to validate the source of the (remaining) problem, but its def. the case that if you are using the TxScope attrib. you should be using the HibernateTxScopeTransactionManager as you've found.

Just so I can be clear in re: the scope of the problem, can you please see if you can also repro the issue with Spring.Net 2.0 RC2 and the latest NH3.x we support?  I'm trying to understand whether the issue is really related to Spring.Net 1.3.2 vs  2.0 or NH3.x vs NH4.x.

Thanks!

-Steve B.

-----Original Message-----

**Comment by piolo108** [comment]
Tested as requested with the following
IPlatformTransactionManager: HibernateTxScopeTransactionManager
spring-net: 1.3.2.40943
nhiberante: 3.2.0.4000

I got the same error as above (https://github.com/spring-projects/spring-net/issues/96#issuecomment-73162888)

**Comment by sbohlen** [comment]
Thanks, I think if the issue is present in SPRNET 1.3.2 + NH 3.2, we'll conclude that it hasn't been introduced as part of any SPRNET 2.0 work.  I think that gives me a good starting point for beginning to puzzle out the source of the issue.  I'll let you know if any further testing would be helpful once I've looked into this a bit further this weekend.

**Comment by sbohlen** [comment]
Could you perhaps provide a PR with a complete test that I can use to repro this issue?  Or failing that could you post the config that relates to the test-code-snippet that you provide here https://github.com/spring-projects/spring-net/issues/96#issuecomment-73162888?

I want to be certain that I'm working with the right repro case...

**Comment by piolo108** [comment]
Is it possible to recreate the issue in a forked repo? or is a standalone project preferred?

**Comment by sbohlen** [comment]
Forked repo with a PR is likely simplest; recommend you create a new test fixture with the test(s) just for this one issue if possible.

-----Original Message-----

**Comment by sbohlen** [comment]
Just circling back on this to see if its possible for you to provide a repro test case for us.  This is the sole remaining open blocking issue preventing our intended 2.0GA release and so I'd like to resolve it (or at least better understand it so that we can intelligently choose not to address it) so that we can roll out the official 2.0GA packages to NuGet as soon as possible.

Thanks!

**Comment by piolo108** [comment]
@sbohlen, I apologize, I can definitely try to have something for you by tomorrow evening, the project is pretty big, I need to track all the spring configuration files which some are as embedded resources from other repositories.

**Comment by sbohlen** [comment]
Understood -- I'm not likely to have cycles to attempt to resolve this until the weekend anyway, so anything you can get me before then would be fine.

Also, if its simpler to provide this in some manner other than a pull-request, please feel free to do that instead (i.e., a separate GitHub repo or other).

Don't get hung up on the mechanics; do what's simplest for you to be able to convey a working (failing) test to us as frictionless as possible.

Thanks again!

-Steve B.

-----Original Message-----

**Comment by piolo108** [comment]
created the following full request "https://github.com/spring-projects/spring-net/pull/101"

**Comment by sbohlen** [comment]
@piolo108:

I just wanted to circle back here to let you know that I've not forgotten about this; quite the contrary, I've been working to try to get to the bottom of this during most of my non-working/non-sleeping hours for the past week.

As mentioned , this is the sole remaining blocker to our 2.0GA release and as of now I'm still hoping/planning to resolve this (soon) and get it into the now-slightly-postponed release.

However, in my attempts to get this back into a working state, I ran the tests you provided against the following combination of dependencies...
* Spring.NET 1.3.2GA components (e.g., Spring.Data)
* NHibernate 3.2

...and I was still unable to get the tests to pass using this combination.  I understood (perhaps incorrectly) that this was a regression bug betw. 1.3.2GA and 2.0.0RC2 (?)

Can you clarify the combination of Spring.NET and NHibernate versions under which these tests were initially passing for you?  I'd like to get a working/passing combination and the now-failing combination together and compare/contrast the points of difference as my next step in trying to isolate the underlying cause of the error here if possible.

Thanks!

**Comment by sbohlen** [comment]
I've also just discovered something else in my subsequent testing -- if I revert to using the `HibernateTransactionManager` (vs. the `HibernateTxScopeTransactionManager`) then your tests here actually pass using both of the following combinations:
* Spring.NET 1.3.2-GA + NHibernate 3.2
* Spring.NET 2.0.0-RC2 + NHibernate 4.x

Based on this, it seems as if you may have uncovered an issue with the `HibernateTxScopeTransactionManager` when used with this combination of nesting of  `TransactionPropogation` values.

I'd like to proceed on two parallel fronts from here if possible:

1. We will try to resolve whatever the issue may be in `HibernateTxScopeTransactionManager` that is making the current tests you've provided fail.  If we're successful here, you could then continue to use the `HibernateTxScopeTransactionManager` in your project.

2. As I understand this thread, you had an initial set of tests (a repro for which I don't think you've yet shared with us) that used `HibernateTransactionManager` and were apparently _passing_ under Spring.NET 1.3.2 but then _failing_ under Spring.NET 2.0.0.  Would it be possible for you to provide us another PR with a set of these tests that you indicated prior were failing when using the `HibernateTransactionManager` but then passing under the `HibernateTxScopeTransactionManager`?  Its likely that these original failing tests of your will uncover another/different set of bug(s) that we would want/need to address as well if possible.

Thanks!

**Comment by piolo108** [comment]
@sbohlen, thank you! I was about to respond to your first update without reading the second :).  For #1, do you mean *pass* instead of *fail*? For #2, to clarify, the project was using a custom TxScopeTransactionManager extending from *HibernateTxScopeTransactionManager*.  Would you like me to run the unit tests using *HibernateTransactionManager* instead of the project's *custom* TxScopeTransactionManager? Using the custom TxScopeTransactionManager with the upgraded Spring.NET 2.0 RC2 assemblies is where this bug initially stemmed from *System.ArgumentException : The transaction specified for TransactionScope has a different IsolationLevel than the value requested for the scope*

**Comment by sbohlen** [comment]
@piolo108:

There are so many different references to pass/fail in my post that I can't even tell what specifically you're asking about re: clarification :)

Here's the present state of affairs from my having run your new TestFixture in the `Spring.SessionFactoryImplError.Tests` project with diff. combinations of versions and TxManagers:

SPRNET ver | NHibernate ver | TransactionManager | Test Result
-------- | -------- | --------- | --------
1.3.2-GA | 3.2 | `HibernateTxScopeTransactionManager` | **FAIL**
2.0.0-RC2 | 4.x | `HibernateTxScopeTransactionManager` | **FAIL**
1.3.2-GA | 3.2 | `HibernateTransactionManager` | **PASS**
2.0.0-RC2 | 4.X | `HibernateTransactionManager` | **PASS**

This leads me to believe that the cause of the failure in at least the specific tests in `Spring.SessionFactoryImplError.Tests` is unrelated to version of either SPRNET or NH.  Instead, its likely some difference in the way this specific combination of nested `TransactionPropagation` settings is handled by `HibernateTransactionManager` vs `HibernateTxScopeTransactionManager`.  We can (and will) investigate this to try to determine what's going on.

At the same time, I was asking if you could provide us the failing tests that you reference in your initial post (https://github.com/spring-projects/spring-net/issues/96#issue-56707905).

My understanding from reading the entirety of this thread was that you started out using `HibernateTransactionManager` and this gave you the error:
```
System.ArgumentException : The transaction specified for TransactionScope has a different IsolationLevel than the value requested for the scope
```
Then, you later switched to `HibernateTxScopeTransactionManager` and this solved that error but introduced this new error instead:
```
System.InvalidOperationException : No value for key [NHibernate.Impl.SessionFactoryImpl] bound to thread [Runner thread]
   at Spring.Transaction.Support.TransactionSynchronizationManager.UnbindResource(Object key)
   at Spring.Data.NHibernate.HibernateTxScopeTransactionManager.DoSuspend(Object transaction)
   at Spring.Transaction.Support.AbstractPlatformTransactionManager.Suspend(Object transaction)
   at Spring.Transaction.Support.AbstractPlatformTransactionManager.HandleExistingTransaction(ITransactionDefinition definition, Object transaction, Boolean debugEnabled)
   at Spring.Transaction.Support.AbstractPlatformTransactionManager.GetTransaction(ITransactionDefinition definition)
   at Spring.Transaction.Interceptor.TransactionAspectSupport.CreateTransactionIfNecessary(ITransactionAttribute sourceAttr, String joinpointIdentification)
   at Spring.Transaction.Interceptor.TransactionInterceptor.Invoke(IMethodInvocation invocation)
```
My understanding (maybe in error?) was that the first error was caused by `HibernateTransactionManager` and the second error was caused by `HibernateTxScopeTransactionManager`.  Your PR contained the failing test demonstrating the error(s) from `HibernateTxScopeTransactionManager` but we don't have any similar tests demonstrating your initial error when using `HibernateTransactionManager`, so that's what I was requesting.

If, as you seem to be clarifying now, you have *always* been using `HibernateTxScopeTransactionManager` (or your own subclass of it) then my whole request for an additional PR is probably unfounded.

If you've been using your own subclass of `HibernateTxScopeTransactionManager` all along, then I'd like to request that you do the following and re-run the entirety of your tests:

1. Swap back in the original/framework instance of `HibernateTxScopeTransactionManager` (this is just a sanity-check and is entirely likely to also FAIL but it will isolate whether your custom impl, has any bearing on your pass/fail results)
2. Swap in the original/framework `HibernateTransactionManager` (based on my results here with your sample test, my guess is that this is more likely to pass for you

Sorry for the long-windedness here, wanted to explain my complete thinking here so that it (hopefully!) makes sense to you where I was coming from in my request.

**Comment by ynauls** [comment]
@sbohlen, below are the results to your request (fyi, changed username)

`
1. Swap back in the original/framework instance of HibernateTxScopeTransactionManager (this is just a sanity-check and is entirely likely to also FAIL but it will isolate whether your custom impl, has any bearing on your pass/fail results)
2. Swap in the original/framework HibernateTransactionManager (based on my results here with your sample test, my guess is that this is more likely to pass for you
`

results coming soon

**Comment by sbohlen** [comment]
OK, understood, thanks for testing this.

re: 1., we're in agreement that this is the expected result but it does help validate that the issue isn't per se in your own subclass of `HibernateTxScopeTransactionManager`.

re: 2., I'm not entirely surprised by this result either; the main diff. between `HibernateTransactionManager` and `HibernateTxScopeTransactionManager` is in re: its handling of scopes and nested propagations so your inability to substitute one for the other without breaking other of your tests is also somewhat expected.

Unfortunately, this leads us back to the two possible paths forward I outlined in https://github.com/spring-projects/spring-net/issues/96#issuecomment-76465726:

1. We'll proceed to try to isolate why `HibernateTxScopeTransationManager` fails in the `Spring.SessionFactoryImplError.Tests` project from your pull request but `HibernateTransactionManager` passes.  Since you've verified that substituting `HibernateTransactionManager` for `HibernateTxScopeTransactionManager` isn't a fix for your use-case, this won't per se help you but its still something that we need to get to the bottom of ASAP (preferably prior to 2.0.0GA).

2. I'd like to request that you assemble another PR if possible that uses `HibernateTxScopeTransactionManager` and demonstrates the initially-reported error `System.ArgumentException : The transaction specified for TransactionScope has a different IsolationLevel than the value requested for the scope`.  This should let us get to the bottom of why you received the initial test failure. 

Would it be possible for you to do this for us?

**Comment by ynauls** [comment]
@sbohlen, thank you for the update, in regards to number 2, "I'd like to request that you assemble another PR if possible that uses HibernateTxScopeTransactionManager...", I got the initial error using our custom/subclass of `HibernateTxScopeTransactionManager`.  Using `HibernateTxScopeTransactionManager` "fixed" the initial error 'System.ArgumentException : The transaction specified for TransactionScope has a different ', but yielded 'System.InvalidOperationException : No value for key [NHibernate.Impl.SessionFactoryImpl] bound to thread [Runner thread]'.  Do you want me to create a pull request with our custom/subclass of `HibernateTxScopeTransactionManager`?

**Comment by sbohlen** [comment]
@ynauls :

Yes, please do -- that would (hopefully) give us a full/complete picture of the situation resulting in both of the different failure(s) you're reporting here.

Thanks!

**Comment by ynauls** [comment]
@sbohlen, I apologize for not replying earlier.  I will have something for you either tomorrow or Sunday.

**Comment by sbohlen** [comment]
Understood; appreciate the update.  FWIW, we're going to release 2.0.0-GA no later than 3/15 so the sooner you can get this to us the better -- we'd like to be able to include a resolution to this issue in the release if possible.

Thanks!

**Comment by ynauls** [comment]
@sbohlen, I have good and bad news. good news: the existing unit tests in `Spring.SessionFactoryImplError.Tests` passes with the Custom TX Scope Manager, however, bad news: I was able to reproduce the original error with the Custom TX scope Manager: 
```
System.ArgumentException : The transaction specified for TransactionScope has a different IsolationLevel than the value requested for the scope
```
I have included the additional test case called `TestSuspendTransactionOnNotSupportedWithNestedRequiresNew` that depicts the original error with the custom TX Scope manager. Included the custom TX Scope manager implementation to the PR called `CustomSpring132HibernateTxScopeTransactionManager`, after digging through repos, i found and noticed that is not a subclass of NH TX Scope Manager, but copy with a few mods.  I left comments that explain the implementation.

There are now two test fixtures, both contain the same unit test, but inject a different TX Scope Manager
1. TestUsingCustomHibernateTxScopeTransactionManager: injects Custom TX Scope Manager
2. TestUsingHibernateTxScopeTransactionManager: Inject NH TX Scope Manager

Please let me know if you have any other question or need assistance.

**Comment by sbohlen** [comment]
Understood; I've pulled from your MASTER to refresh my local branch and have been able to fully reproduce your PASS/FAIL results on my end as well (both the results with the `HibernateTxScopeTransactionManager` and with your custom implementation).

I'll dig into this shortly; thanks for taking the time to provide us a repro case.

**Comment by tikicoloda** [comment]
> Understood; appreciate the update. FWIW, we're going to release 2.0.0-GA no later than 3/15 so the sooner you can get this to us the better -- we'd like to be able to include a resolution to this issue in the release if possible.
> 
> Thanks!

This is AWESOME news! I think I speak for the entire community when I say "Thank You"!

**Comment by sbohlen** [comment]
@ynauls:

After considerable investigation down any number of blind alleys, I have _finally_ identified the source of the 'bug' you've uncovered: it turns out to have been caused by myself -- and intentionally too, it appears :-/

FWIW, after a lot of effort in the debugger, I eventually ended up temporarily back-porting `Spring.Data.NHibernate4` support into the 1.3.2-GA code base as a sort of a sanity-check in order to return to a known-good state where all your tests pass under a combination of SPRNET 1.3.2 and NH4.x.  Prior, I'd only been comparing [SPRNET 1.3.2 + NH3.2] and [SPRNET 2.0.0 + NH32 and/or NH4.x].  Using this back-porting approach, I was indeed able to get your tests to pass properly under SPRNET 1.3.2, which means I had definitive proof that the issue had to be a change introduced between SPRNET 1.3.2-GA and SPRNET 2.0.0-RC2.

A file-by-file DIFF of the contents of the various `Spring.Data.NHibernate##` projects between 1.3.2-GA and 2.0.0-RC2 turned up no changes that might be the cause of this, so I next examined the `Spring.Data` project (since it of course offers the infrastructure upon which the NHibernate support depends).

Sure enough, I soon uncovered the source of the issue: commit https://github.com/spring-projects/spring-net/commit/d06db488492756b838702fac4d04679919e58b32.  If you revert that commit, all your tests again pass (at least the ones using your custom Hibernate Tx Manager) under SPRNET 2.0.0-RC2.

Commit https://github.com/spring-projects/spring-net/commit/d06db488492756b838702fac4d04679919e58b32 was in response to JIRA issue [SPRNET-1444] (https://jira.spring.io/browse/SPRNET-1444).  As you can see from that issue's comment thread, this was actually an _intentional_ breaking behavior change, setting the default the TX isolation level to `Unspecified` instead of `ReadCommitted`.

You can also see from that comment thread that there was some back-and-forth about the merits of introducing this breaking change, whether at the 2.0.0-GA milestone or otherwise as well as a (probably prudent!) suggestion by @lahma that we should consider introducing some config option, etc. that would permit reverting to the original/legacy behavior (e.g., `ReadCommitted`) if desired.  It seems (of course) as if that suggestion got lost along the way and never morphed into an action-item.

As such, the breaking change was left in 2.0.0 but no mechanism (e.g., `UseLegacyDefaultTransactionIsolation = true`) was introduced (yet).

Our next decision now needs to be which of three possible paths to follow:

1. revert https://github.com/spring-projects/spring-net/commit/d06db488492756b838702fac4d04679919e58b32 to restore the prior behavior and release 2.0.0-GA without this breaking change
2. add e.g. a config setting that would flag reverting to the prior default isolation
3. leave the breaking change intact and expose a config setting (probably in the TX config infrastructure) that would permit setting _any_ arbitrary isolation level as the default for your app

Unless we choose 1., IMO 3. is probably the preferred course of action as this would both enable reverting to the 1.3.2-style default isolation as well as permit setting _any_ default you might choose (e.g., future-proof as well as max. flexibility).

Either way, unless we select 1. (which simply undoes the change), either 2. or 3. is going to require a bit of effort in re: extending the config subsystem to accept some sort of new value/setting that controls this behavior.

Thoughts (from everyone!) welcome -- TBH I'm still not totally sold on the idea that the default wouldn't be best-off simply remaining at `ReadCommitted`...

**Comment by ynauls** [comment]
@sbohlen, thank you for looking into this!  doing some research I found this bug https://jira.spring.io/browse/SPRNET-802.  It seems that it used to be `Unspecified` at one point, then it was was changed to `ReadCommitted`.  https://jira.spring.io/browse/SPRNET-1444 does not site the implications of having the default as `ReadCommitted`.  Was this spawned mainly because it deviates from its java sibling?  I advocate for correctness and consistency, however consistency doesn't necessarily translate to correctness :).  I agree with @markpollack, on his comment in https://jira.spring.io/browse/SPRNET-1444, since `ReadCommitted` is the default is most dbs, I would side with path 1
> 1. revert d06db48 to restore the prior behavior and release 2.0.0-GA without this breaking change.

Does Java's default Isolation level `ISOLATION_DEFAULT` translate one to one to  .Net's `Unspecified`?  If it does, then there is merit in setting the Default to `Unspecified`, but with a configuration option to override that for the application as you noted with path 3
> 3. leave the breaking change intact and expose a config setting (probably in the TX config infrastructure) that would permit setting any arbitrary isolation level as the default for your app

as for SPRING NET 2.0 GA, would it make sense to go with path 1
> 1. revert d06db48 to restore the prior behavior and release 2.0.0-GA without this breaking change.

and path 3 for a point release perhaps?
> 3. leave the breaking change intact and expose a config setting (probably in the TX config infrastructure) that would permit setting any arbitrary isolation level as the default for your app

**Comment by sbohlen** [comment]
Nice job finding [SPRNET-802](https://jira.spring.io/browse/SPRNET-802) :)

FWIW, the motivation for [SPRNET-1444](https://jira.spring.io/browse/SPRNET-1444) wasn't just consistency for consistency's sake (betw. SPR and SPRNET) but was actually in support of an effort that had been underway to port much of the Spring AMQP project to .NET (https://github.com/spring-projects/spring-net-amqp).  The difference in default Tx isolation between the Tx advice on the two platforms was resulting in significant friction/differences in the downstream Spring AMQP code that had a dependency on the underlying Spring Tx infrastructure.

I think that your question here is important:

> Does Java's default Isolation level ISOLATION_DEFAULT translate one to one to .Net's Unspecified?

The answer (I think) is **NO**, they aren't perfectly the same.  [`ISOLATION_DEFAULT`](http://docs.spring.io/spring-framework/docs/2.0.x/api/org/springframework/transaction/TransactionDefinition.html#ISOLATION_DEFAULT) is actually a SPR constant rather than a native Java constant and as you can see from that link to the SPR docs, it does have an entirely different meaning than `Unspecified`.  We selected `Unspecified` because at the time we felt that it was semantically closer to `ISOLATION_DEFAULT` than was `ReadCommitted`.

That said, my (re)read of the SPR definition of `ISOLATION_DEFAULT` has me now actually beginning to second-guess that conclusion :-/

SPR has introduced its own constants for Tx isolation whereas SPRNET (still) relies upon the underlying .NET constants to define isolation.  There had been some discussion at one point about porting the SPR isolation level constants over to SPRNET, but that effort hasn't (yet) been undertaken.

If SPR's `ISOLATION_DEFAULT` really does mean...

> Use the default isolation level of the underlying datastore.

...as the SPR docs identify, then in some cases it might actually be that `ReadCommitted` _is_ the right match to the _intent_ of `ISOLATION_DEFAULT` -- i.e., since "the default isolation of the underlying datastore" actually _is_ `ReadCommitted`, perhaps we should just leave it that way (?)

I suppose that the real problem with retaining `ReadCommitted` is that it _is_ the semantic equivalent of `ISOLATION_DEAFULT` for _some_ databases, but not those for which some other Tx isolation is the database default, so its not really a 'universal' equivalent for `ISOLATION_DEFAULT`, but is instead a sort of 'hard-coded' coupling to e.g. SQL Server and/or other DBs where `ReadCommitted` is the default :(

In this context, the 'proper' mitigation for [SPRNET-1444](https://jira.spring.io/browse/SPRNET-1444) may not be simply to change the default Tx isolation from `ReadCommitted` to `Unspecified` but instead to port the SPR Tx isolation constant(s) into SPRNET so that we can actually achieve parity of _intent_ in the value of the default isolation for the Tx advice...

I guess this all leads back to the conclusion that the right thing to do here is to revert the commit(s) that resulted from [SPRNET-1444](https://jira.spring.io/browse/SPRNET-1444) until we can come up with a better way to address the intent of matching `ISOLATION_DEFAULT` from SPR...

Thoughts --?

**Comment by sbohlen** [comment]
BTW, perhaps just to further reinforce this (or maybe just to rub salt in an already painful wound!), note that the code even contains a `//TODO:` for just this refactoring: https://github.com/spring-projects/spring-net/blob/master/src/Spring/Spring.Data/Transaction/Support/DefaultTransactionDefinition.cs#L68 :P

**Comment by ynauls** [comment]
@sbohlen, I agree, I think it will be worth porting SPR Tx isolation constants to ensure that we are  comparing apples to apples.

Rolling back will resolve the original exception using my Custom Tx Scope Manager. 
`System.ArgumentException : The transaction specified for TransactionScope has a different IsolationLevel than the value requested for the scope.
Parameter name: transactionOptions.IsolationLevel.
`
 I can continue using my Custom Tx Scope Manager with SPRNET 2.0 GA.  

How about the error I ran into using NH Tx Scope Manager (https://github.com/spring-projects/spring-net/issues/96#issuecomment-73162888)?  Since this is an existing bug, perhaps this can be looked into in a point release? BTW. a potential fix to that issue is in my Custom Tx Scope Manager.  It's definitely worth a good look by you :)

**Comment by sbohlen** [comment]
With all the focus on the bug, I admit I didn't spend much (any!) time really looking closely at your custom implementation to really understand its differences -- would you be willing/interested in explaining a bit more about why you have a need for a custom TX manager?

Does your custom TX mgr have anything 'custom' that would be inappropriate for everyone to benefit from or is it just various bug-fixes (i.e., could you make the changes as a PR against the existing HibernateTxScopeTransactionManager instead of maintaining your own 'custom' impl)?

I could obviously pick through a DIFF with a fine-tooth comb too, but hoping you could possibly provide more context for the changes you've made...

Thanks!

-----Original Message-----

**Comment by ynauls** [comment]
@sbohlen, definitely, I custom i believe addresses an existing bug in NH Tx Scope Manager. I pushed https://github.com/spring-projects/spring-net/commit/082ee5d0d07890093532bbfba46a4db50dd3c38c,  You can use the `Spring.SessionFactoryImplError.Tests` to validate the effects of the change against `TestUsingHibernateTxScopeTransactionManager.cs` Fixture.  I attempted to explain the logic behind this change in the commit comment :). Please let me know if you have any questions.

**Comment by sbohlen** [comment]
Thanks for the PR; I've reviewed it and I tend to agree with your proposed change(s).  The issue I'm trying to come to terms with now is whether this constitutes so much of a behavior change that we'd need to wait until after 2.0.0-GA to accept it (since its a divergence from the behavior that had been present in 2.0.0-RC2, the most recent RC).

TBH, I really don't want to delay the 2.0.0-GA release long enough for a 2.0.0-RC3 to be released and evaluated, but accepting this PR (probably) means a behavior change from the 2.0.0-RC2 packages that wouldn't have a chance to be broadly evaluated before becoming 2.0.0-GA ... and that carries with it its own potential negative repercussions :(

**Comment by ynauls** [comment]
@sbohlen, since our project is using a Custom TX Scope Manager, this fix I can wait until the next point release (hopefully soon after 2.0)  I know the community has been waiting the 2.0 release for some time now, I share your thoughts on not wanting to delay it any longer :)

**Comment by sbohlen** [comment]
Actually, I've looked at this again and have concluded that its safe to include in the 2.0GA release after all.  I've been interrupted by unexpected business travel, but plan to try to get the 2.0GA release out tomorrow (26 March) after merging this change first.

**Comment by ynauls** [comment]
@sbohlen, awesome news! thank you for all the support.

**Comment by ynauls** [comment]
all unit tests pass!
